-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 分布式锁表（用于防超卖）
CREATE TABLE public.distributed_locks (
  key VARCHAR(255) PRIMARY KEY,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 中介邀请码表
CREATE TABLE public.invitation_codes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code VARCHAR(50) NOT NULL UNIQUE,
  role VARCHAR(20) NOT NULL DEFAULT 'agent',
  is_active BOOLEAN DEFAULT TRUE,
  max_uses INT DEFAULT 1,
  used_count INT DEFAULT 0,
  created_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 支付记录表
CREATE TABLE public.payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  payment_method VARCHAR(20) NOT NULL,
  payment_status VARCHAR(20) DEFAULT 'pending' CHECK (payment_status IN ('pending', 'success', 'failed', 'refunded')),
  transaction_id VARCHAR(255),
  amount DECIMAL(10,2) NOT NULL,
  paid_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 裂变追踪表
CREATE TABLE public.referral_tracking (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  referrer_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  referred_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  status VARCHAR(20) DEFAULT 'registered' CHECK (status IN ('registered', 'first_trade', 'rewarded')),
  reward_amount DECIMAL(10,2),
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE (referrer_id, referred_id)
);

-- 启用RLS
ALTER TABLE public.distributed_locks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invitation_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.referral_tracking ENABLE ROW LEVEL SECURITY;

-- RLS策略
CREATE POLICY "所有人可查看锁" ON public.distributed_locks FOR ALL USING (true);
CREATE POLICY "管理员可管理邀请码" ON public.invitation_codes FOR ALL USING (true);
CREATE POLICY "用户可查看自己的支付" ON public.payments FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.orders o 
    WHERE o.id = order_id AND (o.buyer_id = auth.uid() OR o.seller_id = auth.uid())
  )
);
CREATE POLICY "用户可查看自己的裂变记录" ON public.referral_tracking FOR SELECT USING (referrer_id = auth.uid() OR referred_id = auth.uid());