-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 用户表
CREATE TABLE public.users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  referred_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 用户角色表
CREATE TABLE public.user_roles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  role VARCHAR(20) NOT NULL CHECK (role IN ('demander', 'rights_holder', 'agent')),
  is_active BOOLEAN DEFAULT TRUE,
  UNIQUE (user_id, role)
);

-- 商标表
CREATE TABLE public.trademarks (
  registration_number VARCHAR(50) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(50),
  exclusive_period_end DATE,
  seo_description TEXT,
  owner_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 商标监控表
CREATE TABLE public.monitor_my_trademarks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  registration_number VARCHAR(50) NOT NULL REFERENCES public.trademarks(registration_number) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 上架表
CREATE TABLE public.listings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  trademark_id VARCHAR(50) NOT NULL REFERENCES public.trademarks(registration_number) ON DELETE CASCADE,
  seller_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  auction_type VARCHAR(20) NOT NULL CHECK (auction_type IN ('fixed', 'english', 'sealed', 'multi', 'revenue')),
  current_price DECIMAL(10,2) NOT NULL,
  original_price DECIMAL(10,2),
  min_increment DECIMAL(10,2) DEFAULT 100,
  start_time TIMESTAMP,
  end_time TIMESTAMP,
  is_active BOOLEAN DEFAULT TRUE,
  status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'ended', 'sold')),
  created_at TIMESTAMP DEFAULT NOW()
);

-- 出价表
CREATE TABLE public.bids (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  listing_id UUID NOT NULL REFERENCES public.listings(id) ON DELETE CASCADE,
  bidder_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  amount DECIMAL(10,2) NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 订单表
CREATE TABLE public.orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  listing_id UUID REFERENCES public.listings(id) ON DELETE SET NULL,
  buyer_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  seller_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  agent_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'unpaid' CHECK (status IN ('unpaid', 'paid', 'applied', 'transferred', 'completed', 'cancelled')),
  final_price DECIMAL(10,2) NOT NULL,
  payment_method VARCHAR(20),
  payment_time TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 证据留存表
CREATE TABLE public.user_evidences (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  evidence_type VARCHAR(20) NOT NULL DEFAULT 'usage' CHECK (evidence_type IN ('usage', 'infringement')),
  status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'verified', 'rejected')),
  file_url TEXT,
  description TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 申请服务表
CREATE TABLE public.user_applications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  application_type VARCHAR(20) NOT NULL CHECK (application_type IN ('registration', 'protection')),
  application_status VARCHAR(20) DEFAULT 'pending' CHECK (application_status IN ('pending', 'processing', 'completed', 'rejected')),
  trademark_name VARCHAR(255),
  category VARCHAR(50),
  created_at TIMESTAMP DEFAULT NOW()
);

-- API密钥表
CREATE TABLE public.api_keys (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  api_key VARCHAR(64) NOT NULL UNIQUE,
  rate_limit INT DEFAULT 100,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 启用RLS
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trademarks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.monitor_my_trademarks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.listings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bids ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_evidences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_keys ENABLE ROW LEVEL SECURITY;

-- RLS策略 - 用户表
CREATE POLICY "用户可查看自己的信息" ON public.users FOR SELECT USING (id = auth.uid());
CREATE POLICY "用户可更新自己的信息" ON public.users FOR UPDATE USING (id = auth.uid());

-- RLS策略 - 角色表
CREATE POLICY "用户可查看自己的角色" ON public.user_roles FOR SELECT USING (user_id = auth.uid());

-- RLS策略 - 商标表
CREATE POLICY "所有人可查看商标" ON public.trademarks FOR SELECT USING (true);
CREATE POLICY "权利人可管理自己的商标" ON public.trademarks FOR ALL USING (owner_id = auth.uid());

-- RLS策略 - 监控表
CREATE POLICY "用户可管理自己的监控" ON public.monitor_my_trademarks FOR ALL USING (user_id = auth.uid());

-- RLS策略 - 上架表
CREATE POLICY "所有人可查看上架" ON public.listings FOR SELECT USING (true);
CREATE POLICY "权利人可管理自己的上架" ON public.listings FOR ALL USING (seller_id = auth.uid());

-- RLS策略 - 出价表
CREATE POLICY "所有人可查看出价" ON public.bids FOR SELECT USING (true);
CREATE POLICY "用户可创建自己的出价" ON public.bids FOR INSERT WITH CHECK (bidder_id = auth.uid());

-- RLS策略 - 订单表
CREATE POLICY "用户可查看自己的订单" ON public.orders FOR SELECT USING (buyer_id = auth.uid() OR seller_id = auth.uid() OR agent_id = auth.uid());
CREATE POLICY "用户可创建自己的订单" ON public.orders FOR INSERT WITH CHECK (buyer_id = auth.uid());
CREATE POLICY "用户可更新自己的订单" ON public.orders FOR UPDATE USING (buyer_id = auth.uid() OR seller_id = auth.uid() OR agent_id = auth.uid());

-- RLS策略 - 证据表
CREATE POLICY "用户可管理自己的证据" ON public.user_evidences FOR ALL USING (user_id = auth.uid());

-- RLS策略 - 申请表
CREATE POLICY "用户可管理自己的申请" ON public.user_applications FOR ALL USING (user_id = auth.uid());

-- RLS策略 - API密钥表
CREATE POLICY "用户可管理自己的API密钥" ON public.api_keys FOR ALL USING (user_id = auth.uid());